// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADghEpn5QG_Ro3KnU9ib9vGIJrem3QnGU',
    appId: '1:1057935139437:web:fce69345213287ccab1564',
    messagingSenderId: '1057935139437',
    projectId: 'memoricemobile-9ecd2',
    authDomain: 'memoricemobile-9ecd2.firebaseapp.com',
    storageBucket: 'memoricemobile-9ecd2.appspot.com',
    measurementId: 'G-QHNTN95X9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzOpXq1lQDRPiDSxI5gg6pLN6T6QJEHPA',
    appId: '1:1057935139437:android:d5dcb1640b32fe72ab1564',
    messagingSenderId: '1057935139437',
    projectId: 'memoricemobile-9ecd2',
    storageBucket: 'memoricemobile-9ecd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzxgXBe4toG51X15A42HIDI29MpOgQSk8',
    appId: '1:1057935139437:ios:39520bf6aeb11807ab1564',
    messagingSenderId: '1057935139437',
    projectId: 'memoricemobile-9ecd2',
    storageBucket: 'memoricemobile-9ecd2.appspot.com',
    iosBundleId: 'ulagos.spaceduo.spaceduo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzxgXBe4toG51X15A42HIDI29MpOgQSk8',
    appId: '1:1057935139437:ios:866bd8b5624c3170ab1564',
    messagingSenderId: '1057935139437',
    projectId: 'memoricemobile-9ecd2',
    storageBucket: 'memoricemobile-9ecd2.appspot.com',
    iosBundleId: 'ulagos.spaceduo.spaceduo.RunnerTests',
  );
}
